# Generated by Django 4.2.7 on 2023-11-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
