# Generated by Django 4.2.7 on 2023-11-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CommentPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('comentario', models.TextField()),
                ('visivel', models.IntegerField()),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photos')),
            ],
        ),
    ]
